<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <NuGetAudit>false</NuGetAudit>
    <AssemblyName>TunnelGate.Setup</AssemblyName>
    <RootNamespace>TunnelGate.Setup</RootNamespace>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <PublishTrimmed>false</PublishTrimmed>
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
    <Version>3.1.14</Version>
    <ApplicationIcon>..\Assets\TunnelGate.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Payload\TunnelGate.exe" LogicalName="TunnelGate.Setup.Payload.TunnelGate.exe" />
    <Resource Include="..\Assets\TunnelGateIcon.png" Link="Assets\TunnelGateIcon.png" />
    <Resource Include="..\Assets\TunnelGate.ico" Link="Assets\TunnelGate.ico" />
  </ItemGroup>
</Project>
